### ISSUE TITLE
Modificar Bug

### ISSUE THREAD

**Issue by DavidNiz-A** [Negroove/ProyectoFinal-Prog1#10]
- Permitir al usuario modificar atributos de un bug existente (estado, descripción, prioridad).

-Cuando se quiera modificar una incidencia/bug se le va a pedir el ingreso del id y el usuario va a poder elegir que dato puede modificar.

Datos modificables : 
Nombre, Descripcion, estado, prioridad

- La fecha de finalizacion se cargara  date.now() cuando el estado del bug se encuentre en finalizado

**Comment by DavidNiz-A** [comment]
Queda pendiente implementar fecha de finalización

**Comment by Negroove** [comment]
Continuo con la implementacion de la fecha de finalizaicon cuando se encuentra en estado cerrado
